swig -c++ -java -package com.chiragahuja.imageclassification.app.jni \
    -o java/liblabel_image/src/main/cpp/label_image_wrap.cpp -outdir java/liblabel_image/src/main/java/com/chiragahuja/imageclassification/app/jni/ \
    java/jni/label_image.i