/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.chiragahuja.imageclassification.app.jni;

public class ImageClassifier {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ImageClassifier(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ImageClassifier obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        implJNI.delete_ImageClassifier(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void Init(String model_name, String labels_file_name) {
    implJNI.ImageClassifier_Init(swigCPtr, this, model_name, labels_file_name);
  }

  public void Predict(String image_path) {
    implJNI.ImageClassifier_Predict(swigCPtr, this, image_path);
  }

  public ImageClassifier() {
    this(implJNI.new_ImageClassifier(), true);
  }

}
